export const proposalSeed = 'proposal'
export const identifierSeed = 'identifier'
export const nativeVaultSeed = 'native-vault'
export const LockSeed = 'lock'
export const LockVaultSeed = 'lock-vault'
